apiVersion: v1
kind: Namespace
metadata:
  name: hjasdjkghasdk-prod
  labels:
    environment-id: env_2fd45b28-cf4e-404d-8e4b-5f3c885b85bc
    project-id: project_42d51e48-138c-4a1e-9a2e-91858b886794
    project-name: hjasdjkghasdk
    environment-name: prod
    organization-id: org_1c58789b-c98c-4917-b321-116968ec4f8e
