apiVersion: v1
kind: Namespace
metadata:
  name: hjasdjkghasdk-dev
  labels:
    environment-id: env_2ac17bc4-77ac-4809-95b2-94db835a4018
    project-id: project_42d51e48-138c-4a1e-9a2e-91858b886794
    project-name: hjasdjkghasdk
    environment-name: dev
    organization-id: org_1c58789b-c98c-4917-b321-116968ec4f8e
